apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: localhost
    cert-manager.io/certificate-name: devspace-auth-cert
    cert-manager.io/common-name: ""
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-kind: Issuer
    cert-manager.io/issuer-name: devspace-self-signed
    cert-manager.io/uri-sans: ""
  name: devspace-auth-secret
type: kubernetes.io/tls
data:
  ca.crt: %%CRT%%
  tls.crt: %%CRT%%
  tls.key: %%KEY%%
